accessControl:
  autologinAs: admin
  autologinLocal: true
  localNetworks:
  - 127.0.0.0/8
  - 192.168.0.0/24
  - 192.168.1.0/24
  salt: 1jjovY7wxfFi7NrEuFv6eTAXgmyvECPc
api:
  allowCrossOrigin: true
  key: B508534ED20348F090B4D0AD637D3660
plugins:
  Julia2018PrintRestore:
    _config_version: 2
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1677590400
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1677062400
      _plugins:
        read_until: 1682985600
      _releases:
        read_until: 1683552600
  discovery:
    upnpUuid: e3b59d31-7778-4758-80ee-12ba9a463e4e
  errortracking:
    unique_id: 754e62f6-5624-4fed-a4e5-be911ab81a3a
  gcodeviewer:
    _config_version: 1
  klipper:
    _config_version: 4
    configuration:
      config_path: /home/biqu/printer_data/config/
      confirm_reload: false
      logpath: /home/biqu/printer_data/logs/klippy.log
    connection:
      port: /home/biqu/printer_data/comms/klippy.serial
      replace_connection_panel: false
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: true
    unique_id: 8a5f3c71-9601-481e-82d2-fd62032e53d7
  virtual_printer:
    _config_version: 1
printerProfiles:
  default: _default
serial:
  additionalPorts:
  - /home/biqu/printer_data/comms/klippy.serial
  - /tmp/printer
  autoconnect: true
  baudrate: 250000
  blacklistedPorts:
  - /dev/ttyS*
  port: /home/biqu/printer_data/comms/klippy.serial
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo reboot
    systemShutdownCommand: sudo shutdown
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: VdoRcQLeGTl1wnCydf3KAoEMeN0cipk5
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
webcam:
  stream: /webcam/?action=stream
