_version: 2
admin:
  active: true
  apikey: null
  groups:
  - users
  - admins
  password: $argon2id$v=19$m=65536,t=3,p=4$S+ndOwegFKK0Vupd6/2fcw$ynCsJO9bhaZpv3WsCfDNUhTJA8wDINwAcERwDGS9t6U
  permissions: []
  roles:
  - user
  - admin
  settings: {}
